### ISSUE TITLE
bug: lock closed issues and pull requests workflow

### ISSUE THREAD

**Issue by schalkneethling** [mdn/workflows#71]
```
[Invalid workflow file: .github/workflows/lock-closed.yml#L8](https://github.com/mdn/content/actions/runs/2736049067/workflow)
error parsing called workflow "mdn/workflows/.github/workflows/lock-closed.yml@main": workflow is not reusable as it is missing a `on.workflow_call` trigger
```

**Comment by cw118** [comment]
Hello, I was comparing the `idle` and `lock-closed` workflows and I think this bug may be caused by [this](https://github.com/mdn/workflows/blob/main/.github/workflows/lock-closed.yml#L3), since [`workflow_dispatch` (used for manually running a workflow in the "Actions" tab of a repo) should perhaps be `workflow_call`](https://github.com/mdn/workflows/blob/main/.github/workflows/idle.yml#L4) instead? 

I created #72 for this but I am not really an expert in GitHub Actions so I'm not 100% sure.
